Documentação Dev-App - React Native
StructCE/DocStruct pull request #11
Opened 2024-04-09 19:56 UTC by leopcortes

Documentação do React Native, tecnologia do Squad de Desenvolvimento de Aplicativos mobile
   
* Configuração (feita pelo Tamagui)
* Funcionalidade
* ReactJS vs React Native

2024-04-28 16:53 UTC, PedroAmorimG requested changes
Acho interessante explicar [código especifico](https://reactnative.dev/docs/platform-specific-code) e explicar com mais detalhes os principais componentes nativos.

2024-04-28 16:53 UTC, PedroAmorimG commented on squads/assets/logos-tecnologias/react.png
Na branch Main, foi criada uma pasta de assets para cada squad, acho que seria bom mover a logo para deixar mais organizado.

2024-04-28 16:53 UTC, PedroAmorimG commented on squads/dev-app/react-native.md
Como vamos documentar vários tópicos acho que seria bom criar uma pasta para react native "squads/dev-app/react-native/(arquivos da documentação). O ícone do react não está aparecendo no retype, acho que a possível solução vem com a criação da pasta e a criação do arquivo index.yml para configurar o tópico.

2024-05-05 00:32 UTC, leopcortes commented
Arrumei o icone, mudei o arquivo para nova pasta (no momento ela não aparece porque só tem um arquivo, mas ta lá), coloquei mais um exemplo de native components (não sabia muito bem o que explicar mais, acho que é mais fácil deixar o link pra documentação mesmo) e adicionei a explicação de código específico de plataforma.

2024-05-05 13:55 UTC, PedroAmorimG commented on squads/assets/dev-app/react.png
logo ficou na pasta /dev-app acho q ficaria melhor na dev-app/logos

2024-05-05 14:03 UTC, PedroAmorimG reviewed
Só mudar o icone de pasta

2024-05-05 14:11 UTC, PedroAmorimG approved these changes

2024-05-12 14:56 UTC, merged