Dev-App/Feat/Express
StructCE/DocStruct pull request #22
Opened 2024-05-07 23:43 UTC by MatheusNevs

# Express

- Introdução com essencial sobre Express
- Integração com nossas tecnologias para o back-end (tRPC, Prisma, Lucia Auth)

2024-05-08 15:00 UTC, PedroAmorimG commented on squads/dev-app/express/explicacao.md
> +// Aqui estamos falando pro servidor escutar a porta 3000
Acho que seria interessante falar que outras portas além de 3000 podem ser utilizadas

2024-05-08 15:31 UTC, PedroAmorimG commented on squads/dev-app/express/explicacao.md
> +```
Eu tentei só isso e não gerou nenhum arquivo no diretório. Depois, testei utilizando pnpm init e depois pnpm install express e gerou arquivos. Acho que precisa mudar.
```suggestion
```bash
pnpm init
pnpm install express
```
```

2024-05-08 15:39 UTC, PedroAmorimG commented on squads/dev-app/express/explicacao.md
> +import express from "express"
pra esse tipo de import funcionar no package.json precisa ter um parametro "type": "module".

2024-05-08 15:45 UTC, PedroAmorimG commented on squads/dev-app/express/explicacao.md
a documentação não apresenta o comando para rodar o express. Os arquivos estão em typescript, desse modo, não é possível usar o node diretamente.

2024-05-08 16:12 UTC, PedroAmorimG commented on squads/dev-app/express/integracao.md
> +	if (!session) {
```suggestion
	if (!session || session.fresh) {
```

2024-05-08 16:16 UTC, PedroAmorimG commented on squads/dev-app/express/integracao.md
> +```ts auth/routes/login/github.ts
Esse arquivo não tem ser o server.ts?

2024-05-08 16:23 UTC, PedroAmorimG requested changes
A documentação ta boa. Só uns conselhos pontuais.

2024-05-09 21:35 UTC, MatheusNevs commented on squads/dev-app/express/explicacao.md
> +```
Isso mermo maluco, tinha esquecido que o pnpm não tava iniciado ja

2024-05-09 21:40 UTC, MatheusNevs commented on squads/dev-app/express/explicacao.md
> +import express from "express"
Uai, pra mim funciona aqui. Acho que na verdade é porque eu tinha instalado o pacote @types/express que dá uma tipagem na hora de usar o express, vou colocar pra adicionar esse pacote tbm, beleza?

2024-05-09 21:41 UTC, MatheusNevs commented on squads/dev-app/express/explicacao.md
Vou colocar uma parte para rodar o projeto

2024-05-09 21:42 UTC, MatheusNevs commented on squads/dev-app/express/explicacao.md
Tem que adicionar o tsx no pnpm, esqueci tbm

2024-05-09 22:09 UTC, MatheusNevs commented on squads/dev-app/express/integracao.md
> +	if (!session) {
Num entendi, por que teria que ser "se nao tem session ou nao tem session.fresh adiciona um cookie com a session"?

2024-05-11 10:27 UTC, PedroAmorimG commented on squads/dev-app/express/integracao.md
> +	if (!session) {
Se ele ainda tiver um sessão salva nos cookies mas a sessão expirou ela tem que ser limpa dos cookies

2024-05-12 13:31 UTC, MatheusNevs commented on squads/dev-app/express/integracao.md
> +	if (!session) {
Ah ta, tinha olhado pro if de cima por isso que nao tinha entendido

2024-05-12 14:02 UTC, PedroAmorimG approved these changes

2024-05-12 15:08 UTC, merged