feat/deploy-projetos-docker
StructCE/DocStruct pull request #37
Opened 2024-09-04 14:58 UTC by Gabrielrs0

Este pull request adiciona uma documentação detalhada sobre o Docker, com foco especial em Dockerfile e Docker Compose. A documentação aborda os principais comandos, diretivas e sintaxes, explicando os conceitos fundamentais de imagens e contêineres, visando melhorar o entendimento geral do uso do Docker.

2024-09-20 06:22 UTC, weldoj approved these changes

2024-09-24 15:42 UTC, MatheusNevs commented
# Alterações/Sugestões

- O comando expose não é somente para documentação, mas também, como você disse na parte da docker compose, para definir as portas que o container abrirá para se comunicar com outros containers. (na parte da dockerfile)
- Explique como é feito o mapeamento das portas usando o comando "ports". Explique que o comando é composto por duas portas "portaDoLocalHost:portaDoContainer", uma porta se refere à porta do container, onde está alocado o conteúdo/projeto, e a outra é a porta do nosso "http://localhost:porta/", por onde teremos acesso ao conteudo do container. (na parte da docker compose)
- Explique melhor a construção das imagens em docker compose, pra quê serve o contexto, e mencione que o contexto pode ser uma URL para um repositório do GitHub, e o image é o caminho local para a Dockefile usada para criar a imagem do projeto. (na parte da docker compose)

# Feedback

- Fora isso, a documentação ta bem massa, achei que ficou bem explicada. Boa my friend Gabriel.

2024-09-24 15:43 UTC, MatheusNevs requested changes
# Alterações/Sugestões

- O comando expose não é somente para documentação, mas também, como você disse na parte da docker compose, para definir as portas que o container abrirá para se comunicar com outros containers. (na parte da dockerfile)
- Explique como é feito o mapeamento das portas usando o comando "ports". Explique que o comando é composto por duas portas "portaDoLocalHost:portaDoContainer", uma porta se refere à porta do container, onde está alocado o conteúdo/projeto, e a outra é a porta do nosso "http://localhost:porta/", por onde teremos acesso ao conteudo do container. (na parte da docker compose)
- Explique melhor a construção das imagens em docker compose, pra quê serve o contexto, e mencione que o contexto pode ser uma URL para um repositório do GitHub, e o image é o caminho local para a Dockefile usada para criar a imagem do projeto. (na parte da docker compose)

# Feedback

- Fora isso, a documentação ta bem massa, achei que ficou bem explicada. Boa my friend Gabriel.

2024-09-26 21:53 UTC, MatheusNevs approved these changes

2024-09-26 21:54 UTC, merged